name: Hourly Stock Data Fetch

on:
  schedule:
    - cron: '30 13-19 * * 1-5'  # 9:30 AM–3:30 PM ET (hourly), Mon–Fri (UTC times)
    - cron: '0 20 * * 1-5'      # 4:00 PM ET, Mon–Fri (UTC time)
  workflow_dispatch:            # Allow manual run from GitHub UI

jobs:
  fetch-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python main.py

      - name: Commit and push results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add stock_data.csv pipeline.log
          git commit -m "Update stock data and logs [skip ci]" || echo "No changes to commit"
          git push
